"""
Configuration package — re-exports all config symbols for convenient imports.

Usage:
    from backend.config import WEIGHTS, JD, CORE_SKILLS, TODAY
"""

from backend.config.weights import (
    WEIGHTS,
    HARD_PENALTIES,
    SOFT_PENALTIES,
    RELIABILITY_WEIGHTS,
    CREDIBILITY_WEIGHTS,
    SKILL_TRUST_WEIGHTS,
    TIER_WEIGHTS,
    DEGREE_WEIGHTS,
)

from backend.config.evidence_taxonomy import (
    EVIDENCE_KEYWORDS,
    CORE_EVIDENCE_CATEGORIES,
    NICE_EVIDENCE_CATEGORIES,
    HARD_REQUIREMENT_KEYWORDS,
    CORE_SKILLS,
    SECONDARY_SKILLS,
    HIGH_VALUE_AI_SKILLS,
    CONSULTING_FIRMS,
    RELEVANT_FIELDS,
)

from backend.config.job_profile import (
    JD,
    AI_ML_TITLES,
    ADJACENT_TITLES,
    NON_TECH_TITLES,
    PREFERRED_CITIES,
    ACCEPTABLE_CITIES,
    TODAY,
    TOP_K,
    ENGINE_DIR,
    PROJECT_ROOT,
    DATA_DIR,
    SAMPLE_CANDIDATES_PATH,
    INTEGRITY,
)

__all__ = [
    # Weights
    "WEIGHTS", "HARD_PENALTIES", "SOFT_PENALTIES", "RELIABILITY_WEIGHTS",
    "CREDIBILITY_WEIGHTS", "SKILL_TRUST_WEIGHTS", "TIER_WEIGHTS", "DEGREE_WEIGHTS",
    # Keywords
    "EVIDENCE_KEYWORDS", "CORE_EVIDENCE_CATEGORIES", "NICE_EVIDENCE_CATEGORIES",
    "HARD_REQUIREMENT_KEYWORDS", "CORE_SKILLS", "SECONDARY_SKILLS",
    "HIGH_VALUE_AI_SKILLS", "CONSULTING_FIRMS", "RELEVANT_FIELDS",
    # Job profile
    "JD", "AI_ML_TITLES", "ADJACENT_TITLES", "NON_TECH_TITLES",
    "PREFERRED_CITIES", "ACCEPTABLE_CITIES", "TODAY", "TOP_K",
    "ENGINE_DIR", "PROJECT_ROOT", "DATA_DIR", "SAMPLE_CANDIDATES_PATH", "INTEGRITY",
]
